name: planta_care
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  collection: ^1.19.1
  
  dio: ^5.8.0+1

  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.5

  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17

  flutter_swipe_button: ^2.1.3
  flutter_keyboard_visibility: ^6.0.0
  visibility_detector: ^0.4.0+2

  flutter_localization: ^0.3.1

  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/svg/
    - assets/images/
    - assets/images/plants/
    - assets/images/experience_level/
    
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/urbanist/Urbanist-VariableFont_wght.ttf
